Feature/we work for
lexanikitin/everland pull request #6
Opened 2022-08-12 11:10 UTC by SashkaStudent

2022-08-12 12:59 UTC, lexanikitin commented
сейчас свою добью до пулреквеста и будем ревьюить друг друга )

2022-08-12 15:52 UTC, lexanikitin requested changes
Есть вопросы по коду : 

1.  файл blocks/link/_size/link_size_purpose.css мне кажется индивидуализацию базового класса button надо делать в блоке секции (purpose) , создав там элемент purpose__link и в нем переопредели нужные свойства. Таким образом у линка будут классы link purpose__link . Смысл в том, чтобы удержать все индивидуальные свойства , присущие блоку purpose  в нем самом. А блок link содержит только свойства общие для всех линков на странице. 
2. Необычное разрешение для брейкпоинта между дектопом и планшетом. В чем логика ? Карточки ломаются сильно. Не настаиваю, просто заметил необычность. 
3. В этих файлах есть закомментированный код , думаю он лишний : 
blocks/purpose/__cards/purpose__cards.css
blocks/purpose/__description/purpose__description.css
4. Есть устоявшееся мнение об использовании тега img только для контентно значимых изображений, мне кажется иконки можно было в div в качестве background.
5. Заголовок карточки в макете помечен как h4 , а в коде h3. (на стили не влияет, но всетаки)
6. В файле index.html можно удалить демонстрационную секцию.
7. index.html хорошо бы пройти форматтером кода, т.к. теги открытия и закрытия скачут немного друг относительно друга. Будет проще читать.

2022-08-13 08:46 UTC, lexanikitin approved these changes

2022-08-13 19:27 UTC, SergeyKukhtalevV commented
1. На мобильной верстке небольшое несоответствие макету 
![image](https://user-images.githubusercontent.com/106655509/184507910-1691cba8-fed8-40ef-9f64-60d688403171.png)
2.  В некоторых файлах css есть лишние пустые строки перед закрывающей фигурной скобкой или в медиа запросах (например purpose__content.css, purpose__link.css
3. В файле purpose.css нет отступов.

2022-08-14 05:32 UTC, SergeyKukhtalevV approved these changes

2022-08-14 10:54 UTC, merged